Import('*')

# Define the SimObject and its independently organized implementation units.
SimObject('AmxAccl.py', sim_objects=['AmxAccl'])
Source('amx_accl.cc')
Source('amx_execution.cc')
Source('amx_instruction.cc')
Source('amx_latency.cc')
Source('amx_memory.cc')
Source('amx_resource.cc')
Source('amx_scheduler.cc')
Source('amx_sim_object.cc')
Source('amx_tile.cc')

DebugFlag('AMX')
